# ── cloudbuild.yaml ───────────────────────────────────────────────────────────
# Auto build & deploy on git push.
# Replace "wealth-app-yourname" with your actual GCP project ID.

steps:
  # ── Backend ──────────────────────────────────────────────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    id: "build-backend"
    args:
      - build
      - -t
      - "gcr.io/$PROJECT_ID/wealth-backend:$COMMIT_SHA"
      - -t
      - "gcr.io/$PROJECT_ID/wealth-backend:latest"
      - ./backend

  - name: "gcr.io/cloud-builders/docker"
    id: "push-backend"
    waitFor: ["build-backend"]
    args: ["push", "gcr.io/$PROJECT_ID/wealth-backend:$COMMIT_SHA"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-backend"
    waitFor: ["push-backend"]
    entrypoint: gcloud
    args:
      - run
      - deploy
      - wealth-backend
      - --image=gcr.io/$PROJECT_ID/wealth-backend:$COMMIT_SHA
      - --region=asia-south1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --memory=512Mi
      - --set-secrets=DATABASE_URL=DATABASE_URL:latest,REDIS_URL=REDIS_URL:latest,SECRET_KEY=SECRET_KEY:latest,ALPHA_VANTAGE_API_KEY=ALPHA_VANTAGE_API_KEY:latest

  # ── Frontend ──────────────────────────────────────────────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    id: "build-frontend"
    args:
      - build
      - -t
      - "gcr.io/$PROJECT_ID/wealth-frontend:$COMMIT_SHA"
      - -t
      - "gcr.io/$PROJECT_ID/wealth-frontend:latest"
      - --build-arg
      - "VITE_API_URL=${_BACKEND_URL}"
      - ./frontend

  - name: "gcr.io/cloud-builders/docker"
    id: "push-frontend"
    waitFor: ["build-frontend"]
    args: ["push", "gcr.io/$PROJECT_ID/wealth-frontend:$COMMIT_SHA"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-frontend"
    waitFor: ["push-frontend"]
    entrypoint: gcloud
    args:
      - run
      - deploy
      - wealth-frontend
      - --image=gcr.io/$PROJECT_ID/wealth-frontend:$COMMIT_SHA
      - --region=asia-south1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --memory=256Mi

# Pass your backend URL as a substitution variable when triggering this build
substitutions:
  _BACKEND_URL: "https://wealth-backend-142444993823.asia-south1.run.app"
images:
  - "gcr.io/$PROJECT_ID/wealth-backend:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/wealth-frontend:$COMMIT_SHA"
